- Segments/Kesmai.mapproj
All sand components (id = 18), did not have a movement cost assigned. May have been lost at some point, or possibly not generated?
Resolves #452
Resolves #234
> Fix MovementCost for all sand terrain components in Kesmai

- Segments/Axe Glacier.mapproj
- Segments/Leng.mapproj
- Segments/Oakvael.mapproj
- Segments/Underkingdom.mapproj
Tweaked Oak xp since it was far above the other lands / UK values (pulled from lors on the more accurate emulated server + info from the archives.kesmai site). 
Hopefully added the ability to trade (temporary) items to Vulcan, Silvermoon, and Puck. - Need Buddha and Obsidian Egg added. Crystal Gaunt quest might be more in depth but figured for now trading a kill item off Shidosha to Puck works.
Forgot UK treasure - will add later. Need to do a full rebalance of treasure + get more gems added //TODO
Added static names to a lot of vendor NPCs from name generators - I've noticed a lot of feedback that vendors being named the same between facets is a nice quality of life improvement.
> UK and a lot of tweaks

- Segments/Axe Glacier.mapproj
- Segments/Kesmai.mapproj
- Segments/Leng.mapproj
- Segments/Oakvael.mapproj
- Segments/Underkingdom.mapproj
Kesmai surface difficulty nerf - much needed to keep new players safer. It's also more in line with OG stats.
Balm drop % increase globally- should be helpful to new players, minimal bonus to old players.
Various balances to mob hit points / damage. Not a big priority just minor changes.
Massive XP overhaul to every zone except Kesmai - Normal monsters have been brought to "OG Values" except in 2 zones where difficulty had been increased (Leng Waterfall level and Gryphon Cliffs - XP is above OG levels here but should be balanced in regards to difficulty. Thought is it will add another 16+ hunting zone that people will optimize aside from TT/UK).
Several minor tile changes for static component / LOS issues.
instantCast = true, has been added to the majority of mob spells. Context from Lux …
> Massive Balance Changes.

- Segments/Leng.mapproj
This PR includes a minor change to the Leng segment. In Leng Maus the female wizard NPCs were using a male chant/death sound. This is a potential fix for that issue. I have also updated Leng Maus NPC names to be randomized similar to the Kesmai segment.
- Fixed female wizard NPC in Leng Maus to use the correct sounds
- Changed wizard NPC names to be randomized similar to Kesmai segment
> Leng Maus - Fix female wizard NPC sounds and add random names for wizard NPCs

- Source/Kesmai.WorldForge/UI/Documents/SpawnsDocument.xaml.cs
Quick Fix to Worldforge to fix remove region spawner button.
> Fix to Worldforge not removing Region Spawner

- Segments/Kesmai.mapproj
- Segments/Leng.mapproj
- Segments/Oakvael.mapproj
Corrected the following tiles where there should have been a FloorComponent.
Segment RegionID RegionName      X  Y  Issue
------- -------- ----------      -  -  -----
Kesmai  14       Dungeon -4      22 23 Single StaticComponent, potentially navigable
Kesmai  14       Dungeon -4      24 26 Single StaticComponent, potentially navigable
Kesmai  9        Hall of Legends 7  2  Single StaticComponent, potentially navigable
Leng    10       Mausoleum       39 7  Single StaticComponent, potentially navigable
Leng    10       Mausoleum       39 8  Single StaticComponent, potentially navigable
Leng    10       Mausoleum       40 8  Single StaticComponent, potentially navigable
Leng    10       Mausoleum       7  12 Single StaticComponent, potentially navigable
Leng    236      Rift -200       3  0 …
> Replace Static tile components

- Source/Kesmai.WorldForge/Editor/Filters/TerrainSelector.cs
- Source/Kesmai.WorldForge/Editor/MVP/Presenters/ApplicationPresenter.cs
- Source/Kesmai.WorldForge/Game/PresentationTarget.cs
- Source/Kesmai.WorldForge/Game/Screens/WorldGraphicsScreen.cs
- Source/Kesmai.WorldForge/UI/Documents/SpawnsDocument.xaml
- Source/Kesmai.WorldForge/UI/Documents/SpawnsDocument.xaml.cs
Added scaling and a world render to spawns. Also added a filter to show teleportcomponents and a hotkey to display coordinates on world renders.
Known issue: spawn document renders don't work right until BOTH tabs have had a selection made. Unsure why, I tried cloning the presentation and graphics screens into a region and location specific version with the same issue.
> World forge enhancements

- Segments/Axe Glacier.mapproj
- Segments/Kesmai.mapproj
- Segments/Leng.mapproj
- Segments/Oakvael.mapproj
- Segments/Underkingdom.mapproj
Fixed a few places that got missed in previous pass. statics under secret doors, floors under indestructible walls, etc.
Also changed the Leng bushes to static instead of a tile with two floors. Updated the other floor to have the 2 movement cost instead. this was 30-ish replacements across the regions.
Updated Yasnaki level spawns so that they didn't spawn in Shelob's lair, and had a distinct spawner for the area between Shelob and Carfel.
in Oak, I gave the thief trainer an exclusion region and set the thief portal hexes to affect NPCs in order to keep the wildlife out.
> Tile fixes and a few spawn edits

- Segments/Oakvael.mapproj
- Changed region typo from 255 to 225 for teleport on second Knight quest.
> Oakvael Reptile Pit Teleport

- Segments/Underkingdom.mapproj
- Lowered skill level of mummy mobs. These come in packs of 6+ and aren't blockable as it stands.
> UK - Mummy Reskill

- Segments/Oakvael.mapproj
Changed the following:
- Made salamanders immune to fire
- Turned off their ability to loot since they are monster/creatures.
> Minor Fix to Oak Salamanders

- Segments/Axe Glacier.mapproj
- Segments/Leng.mapproj
- Segments/Oakvael.mapproj
- Segments/Underkingdom.mapproj
Added hide detection attributes to all the mobs in Axe, Leng, Oak and UK. I left Kesmai alone, and the surface/easy areas of all the other lands. I based these detection levels on a chart I had from the original GS version of the game. Obviously they can be tweaked, but it'll make it more challenging than it is right now to get a level 3 thief rdaggers, doom bow, etc...
> Added Hide Detection to Various Lands

- Source/Kesmai.WorldForge/Editor/Clipboard/ClipboardManager.cs
- Source/Kesmai.WorldForge/Editor/MVP/Models/Game/Entity.cs
- Source/Kesmai.WorldForge/Editor/MVP/Models/Game/Spawner.cs
- Source/Kesmai.WorldForge/Editor/MVP/Presenters/ApplicationPresenter.cs
- Source/Kesmai.WorldForge/Editor/Tools/ArrowTool.cs
- Source/Kesmai.WorldForge/Editor/Tools/PaintTool.cs
- Source/Kesmai.WorldForge/Game/Screens/WorldGraphicsScreen.cs
- Source/Kesmai.WorldForge/Game/UI/Controls/PropertyGrid/CheckComboBoxPropertyEditor.cs
- Source/Kesmai.WorldForge/Game/UI/Windows/ComponentsWindow.cs
- Source/Kesmai.WorldForge/UI/Documents/EntitiesDocument.xaml
- Source/Kesmai.WorldForge/UI/Documents/EntitiesDocument.xaml.cs
- Source/Kesmai.WorldForge/UI/Documents/LocationsDocument.xaml
- Source/Kesmai.WorldForge/UI/Documents/SpawnsDocument.xaml
- Source/Kesmai.WorldForge/UI/Documents/SpawnsDocument.xaml.cs
- Source/Kesmai.WorldForge/UI/Documents/SubregionDocument.xaml
- Source/Kesmai.WorldForge/UI/Documents/TreasuresDocument.xaml
- Source/Kesmai.WorldForge/UI/Documents/TreasuresDocument.xaml.cs
Enhancements:
* Paint tool now behaves like Draw tool in that a painted floor-type component will overwrite other floor-type components. Append instead with Shift. Paint ONLY the selected component and clobber all existing components with ALT.
* When using the delete hotkey, Only currently visible components are deleted from the selected tile. Filter to floors to remove floor-type components, etc.
* When pasting from the clipboard, the behavior is changed if the target selection is more than 1x1. Old behavior, or if the target selection is 1x1: whole clipboard is pasted in starting with the top left tile as the current selection. New behavior if the target selection is larger than 1x1: the clipboard is tiled horizontally and vertically to fill the selected space. Clipboard tiles that …
> World forge

- Segments/Kesmai.mapproj
This was a response to a suggested breaking up of the zone-wide spawns. -1 and -2 were left alone, but I broke the surface, -3 and -4 into smaller sub-spawners.
The net density of mobs should remain the same across the zone, but any given 7x7 screen may have a slightly different distribution. For example, the lower right quadrant of -3 is more dense than the area around the Leng portal, allowing a softer entry into -3 from -2 or the surface. Another effect of splitting these spawns is that DPiles will wander a shorter distance, since the mobs that killed a player would normally stay within their spawner.
If this is accepted and desired, I'll give a similar treatment to other huge spawners in OG lands.
> Kesmai Spawn tweaks

- Source/Kesmai.WorldForge/Editor/MVP/Models/World/Components/Environmental/TreeComponent.cs
Fixes:
*Fixed crash when a treeComponent doesn't have a dead\alive pairing defined. WorldForge will default to a regular burned tree in this case.
> WorldForge 1/22

- Segments/Blackburrow.mapproj
- Fixed the portable hexes that allowed you to portal around Jym the Giant
- Fixed the teleport hex in the thief bypass to allow mobs to chase you into the secret room. 
- Removed the region spawn from the stairs down to -1 so you don't get inundated with mobs the second you come downstairs. I think this will need more balancing but I want to make small adjustments.
- Added a few roaming skeleton archers with high hide detection to make the final encounter more challenging for thieves. 
- Lowered the drop rate slightly on the high end, high value gems.
> Updates and Fixes for Blackburrow

- Source/Kesmai.WorldForge/Editor/MVP/Presenters/ApplicationPresenter.cs
- Source/Kesmai.WorldForge/UI/ApplicationWindow.xaml
- Source/Kesmai.WorldForge/UI/Documents/EntitiesDocument.xaml
- Source/Kesmai.WorldForge/UI/Windows/WhatsNewWindow.xaml.cs
Enhancements:
* When saving a segment, all script sections are checked for correct syntax. Mismatched brackets or missing semicolons should be called out here. If prompted that there are syntax errors, choosing not to continue will abort the save action and jump to the script with an issue.
* Removed close option from Region Tabs. Resolves #1219
> WorldForge 1/28

- Segments/Kesmai.mapproj
Tried to do them by dungeon level but they only make sense to do zone wide with the changes to drops. I have 100% confidence in this pull
Added:
Orbs to every mob
Gold drop balance
Zone wide gems
Mob archetype drop rates
Yttril will now be found -3 and later, drop rates can be adjusted later easily.
Spawns have been split to have a 50% weight for the entire zone, then 12.5% split up between 4 different quadrants ensuring that mobs will always respawn on certain areas of map.
Wand drops to caster mobs.
No changes to monster balance themselves.
> Kesmai Changes

- Segments/Blackburrow.mapproj
- Expanded the spawn region of skeleton archers
- Instead of making the poison elemental cast PC, I made his attacks with the bow (hopefully) poisonous and made him see hidden targets.
> Further Blackburrow Throne area tweaks

- Segments/Axe Glacier.mapproj
Gem drops increased on Surface / Lightning mesa, value has been normalized.
Starting on Lightning Mesa gems drop 4.8% of the time and increase accordingly. Look out for gold nuggets, they're very valuable now.
Southwest shopkeeper can now carry FireIceProtection
Shopkeepers are now invulnerable
Shield penetration has been normalized. Lower level monsters have VeryLight, with penetration going up to Medium in Chaos Town
Giant castle monsters are now harder (Chaos Town difficulty)
Undead region spawns have been changed - Frosties are less difficult.
Amount of prones has been decreased drastically on drake, mama and yeti.
> Update Axe Glacier.mapproj

- Segments/Axe Glacier.mapproj
- Segments/Leng.mapproj
- Segments/Underkingdom.mapproj
Shidosha is now a level 12 instead of 14 boss - defense rating, damage and hit points have been decreased since last pull.
Armor has been universally dropped on monsters wearing armor to compensate for the values.
UK gems have become more rare to 7.2 in tunnels to 14.6 in Yasnaki depending on level.
> Shid changes and armor balances

- Segments/Axe Glacier.mapproj
- Segments/Leng.mapproj
- Segments/Oakvael.mapproj
- Segments/Underkingdom.mapproj
Boss and Martial Artist monster formula has been adjusted to have lower armor class. Now it's a +1 per level, higher level monsters it will be more noticeable on. (level 14 major boss Mama went from 1,750 to 1,600 defense rating for example).
Shidosha base dodge has been reduced, hit points increased slight. **Number of prones has been drastically decreased.**
Death resistance ring has been added to Leng loot tables for Maus / Cliffs.
Death Resistance Bracelet has been added to Oak loot tables from 2 - 4.
Strong shielders have been removed from OG loot tables except on vlad, mama, and Yasnaki level loot tables at a low %.
Leng Undead has had the number of potential casters spawned lowered. (4 liches can now be on the level instead of potentially 20 for example)
Yeti Ice Storm has been …
> Armor class changes

- Segments/Underkingdom.mapproj
Currently if Guardian kills himself, it has a race condition and causes the item to not drop. This PR adds a fixed position (middle hex in the room).
> Fix Hummer to drop at fixed location

- Segments/Axe Glacier.mapproj
Gems will now be Undead area gems at 10x drop rates from other monsters
Frost giants should use concussion as originally intended now
> Frost giant minor update

- Segments/Axe Glacier.mapproj
adjusted Mama to not roam on the ledge - this allows for players to strategize as a group
Also reduced Mama spawn timer
Updated prone chances and loot from Giant - there's not really a good reason to go to the Giant, as he's harder than Kosh with a worse payout. He's still harder than Kosh, but at least there's a potion chance now
undead treasure
changed the treasure from the undead area to be specific, not just upper glacier - dropped the lower level items, added low chance of dex - loot more in line with higher level area
> Balancing changes in Axe

- Source/Kesmai.Server/Game/Items/Equipment/Shields/LightningShield.cs
- Source/Kesmai.Server/Game/Items/Equipment/Shields/PlatedShield.cs
- Source/Kesmai.Server/Game/Items/Equipment/Shields/SteelShield.cs
- Source/Kesmai.Server/Game/Items/Equipment/Shields/WoodenShield.cs
Proposal to make shields a little better and more useful:
- Set wooden shield to +1 projectile protection
- Set Plated shield to +2 projectile protection
- Set steel shield to +3 projectile protection
- Set lightning shield armor bonus to 2, and +4 projectile protection.
These changes would help everyone using shields.. and would pair well with the new caster wand to give casters more survivability. 
They would provide a boost to the mace/shield combo for knights, but wouldn't over power any of the other weapons.
> shield change proposal

- Segments/Kesmai.mapproj
- Source/Kesmai.Server/Game/Items/Equipment/Armors/LizardScales.cs
- Source/Kesmai.Server/Game/Items/Equipment/Armors/SalamanderScales.cs
- Source/Kesmai.Server/Game/Items/Equipment/Jackets/GriffinJacket.cs
- Source/Kesmai.Server/Game/Items/Equipment/Jackets/GrizzlyJacket.cs
- Source/Kesmai.Server/Game/Items/Equipment/Jackets/PolarBearJacket.cs
- Source/Kesmai.Server/Game/Items/Equipment/Jackets/SharkJacket.cs
- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Maces/SpikedClub.cs
armor progression fix, there is now a clear prgression of armors for the early (pre dragon scale) armors
skulls now only come from lairs in kes.
Trog difficulty reduced to incorporate into armor and skull path.
Implemented some purpose for jackets.  Can be used until robes become better or by ma pre kimono.
Removed some rings from -3 that dropped before element was encountered
> Kesmai early progression update

- Segments/Leng.mapproj
add Manticora to drake, adjusted timers
Split drake from minions to ensure respawn timer
added hallway to roam
Bumped down number of concussion wiz and up number of fire wiz to better align with difficulty at level
Reworked waterfall zones with indestructible walls and obstructions, more area coverage and put a mob in the safe zones
doom duck and tiger larger roam
Cleared up deadspot in undead
let power troll roam
> reduce easy scripting areas from leng

- Content/Localization/Enu.xml
- Source/Kesmai.Server/Game/Items/Equipment/Gauntlets/KoshGauntlets.cs
Changed the Kosh Gauntlet identify messages to a unique description:
"a pair of gauntlets made from leathery dragon skin with shiny blue-steel plates. The Gauntlets emit a Blue Glow."
> Change Kosh Gaunt description (updated and ready for review)

- Source/Kesmai.Server/Game/Items/Equipment/Gauntlets/CrystalGauntlets.cs
- Source/Kesmai.Server/Game/Items/Equipment/Gauntlets/SwiftGauntlets.cs
- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Swords/BlackBroadsword.cs
- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Swords/HummingbirdSword.cs
Certain treasures don't have value to them. A BBS sells for 1 coin, or CGs for 1. It impacts the experience awarded when broken.  You would now get 15k experience for breaking someone's BBS.
> Increase value of certain treasure items.

- Segments/Axe Glacier.mapproj
- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Daggers/MisericordeDagger.cs
Proposal to change Misericorde dagger to a less-powerful version of the BBS (Medium armor pen compared to Very Heavy, 1-10 damage instead of 2-12).
It will drop from yeti and bind to the person who gets the killing blow so no recall for twinking people.
It will also not be a returning weapon.
I believe there will be zero impact to balance but will make dagger players happy.
> Changes to Misericorde Dagger and how it drops

- Segments/Oakvael.mapproj
- Segments/Underkingdom.mapproj
After a long discussion with the fellas in voice chat, we decided it would be better to toss my new Main Gauche defense dagger on the Lich Twins. They are underutilized, and they are a relatively low barrier to entry for a thief. 
For now I have it dropped in the container, I realize that this could be easily abused but traditionally the Lich twins use hand skill so I didn't want to mess that up.
> Main Gauche added to Lich twins

- Segments/Axe Glacier.mapproj
Added a Thief Trainer to lockpick town, giving thieves a training option that allows them the ability to push gold from a bank. 
Created a Thief area behind a secret door to the north of the wizard trainer in lockpick. 
Second Commit added a teleporter to keep the riff raff out of the thieves guild.
> Thief Trainer in Lockpick Town

- Segments/Underkingdom.mapproj
- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Daggers/MainGauche.cs
Ok, I need a little help from the big boys on this one. I want to take the throwable flag off the Main Gauche so it just sits in your offhand like a regular weapon (it's really too big of a dagger to throw anyway) and allow the thief to press / and throw his rdagger from the main hand without it launching the blocking weapon.
So what I did:
- Removed base.flags from MainGauche.cs and inserted the weapon flags I wanted to keep from the dagger base class. This should remove the throwable/quickthrow flags from the base dagger class?
@jkachhad  Does this work the way I think it does? Appreciate some help/input, or even better.. .if you know a way to fix this issue that doesn't require us to remove the throw flags.
> Throwable preference on Main Gauche

- Segments/Underkingdom.mapproj
Converting the gargoyle to a more appropriate monster, and toning it down to one that spawns every 7-10 minutes instead of 3.5 - 5.
Has high attack value, has poison, but doesn't respawn like crazy and punish people trying to hunt in the zone.
Between the pillar and a single monster this will adequately stop scripting without going overboard like it is now according to feedback.
> UK Gargoyle converted to lurker

- Segments/Axe Glacier.mapproj
- Segments/Kesmai.mapproj
- Segments/Leng.mapproj
- Segments/Oakvael.mapproj
- Segments/Underkingdom.mapproj
Exactly the same fix on all appropriate maps.
gemsPriceMutatorMedium was intended to be a modifier of -40% to +nothing. Instead it was doing -40% to + 100%
gemsPriceMutatorAboveAverage was intended to be a modifier of + nothing to +40%. Instead it was doing +100% to +40%
Also update the comments on every mutator to reflect the correct values
> Bug fix for Gem Price Mutators and correct comments

- Segments/Axe Glacier.mapproj
Dungeon of Doom is only accessible on route between Ogre Caves (a level 10 area) and Undead (a level 16 area).
Currently the area was spawning Level 8 creatures. I believe an oversight due to it descending where all other progression in Axe ascends.
I have made Level 13 version of most creatures on this level by copying Level 10 version  and then applying similar exp and health etc values from the same or similar creatures of level 13 in Leng.
I know its a fairly big update and will need testing but currently the area makes no sense as its regressing before a massive jump up. I believe this should be in keeping with the area while providing progression between the areas
> Upgrade Dungeon of Doom

- Segments/Kesmai.mapproj
- Segments/Underkingdom.mapproj
Sewer modifier was in when we were originally using the -100 tunnels monster values. With new system experience modifiers are unneeded (but should we go with Kora's ideas of weighting zones for gold/xp/loot balance we can edit as needed).
> Fixed an issue where experience modifier artifacts remained

- Source/Kesmai.WorldForge/Editor/TerrainManager.cs
- Source/Kesmai.WorldForge/Game/GameSprite.cs
Minor tweak. When revisiting existing sprites WF currently prefers art in the BIN files. This changes it to prefer art in the Content directory if present.
Also, if a terrain references a file that doesn't exist (typo in png name or missing file) do not populate the mgcb file with that art.
> WorldForge - prefer new art assets over BIN art

- Segments/Oakvael.mapproj
her body was never defined so it was defaulting to 1 (efreet)
> Fix pescalanor art

- Segments/Oakvael.mapproj
Oak UD is in pretty good shape, with the exception of loot and the banshees. 
This first change is a small tweak in damage:
32.4 damage a cast per pack --> 27.6 damage per pack
Banshee mana from 11 -> 6  (3 cast per pack, with 1 primed to go... down to 2 cast per pack)
This will reduce the burst damage from having multiple packs of banshees... and bring them back to 2 cast per pack. 
The rest of Oak UD feels pretty good to me, sans some lack of itemization. 
And sorry for the two-commit thing... I tweaked it down to skill level 2, and then changed my mind and split the difference.
> Oak UD Tweak to Banshees

- Source/Kesmai.WorldForge/Editor/MVP/Models/Game/Entity.cs
- Source/Kesmai.WorldForge/Editor/MVP/Models/Game/Spawner.cs
- Source/Kesmai.WorldForge/UI/Documents/EntitiesDocument.xaml
- Source/Kesmai.WorldForge/UI/Documents/SpawnsDocument.xaml
The idea is to give a figure we can compare and see at a glance if something may currently be giving out too much or to little XP based on its stats.
The resolution of an anomaly could be to change a combination of the XP, or the Skill or the Health of  the creature to balance it.
Initially a value around 3.5 seems to be about in keeping. Values off this May want looking at.. but this is just a tool and its far from exact. It can sometimes highlight a creature has Something wrong.
Currently Magic threat values are approximated on "Magic" values and these could need adjusting.
There are also a couple of improvements that could be made in the calculations if this is proving useful and wanted.
As this doesnt already exist as such - it should not adversely effect the editor, its simply new …
> Calculate a figure for XP per Threat and Health

- Source/Kesmai.WorldForge/Editor/MVP/Models/Game/Spawner.cs
- Source/Kesmai.WorldForge/Game/Screens/WorldGraphicsScreen.cs
Make overlapping spawn regions more readable by indenting multiple regions slightly that originate in the same space + text always on top so multiple regions don't obscure previous text + make exclusions always show first and say what zone they are an exclusion for.  Also showing the estimated average threat level for the region in the (melee, ranged, magic) threat level format.
Again, this is not effecting the game at all - just improving the editor. I put some before and after pictures in Dev channel.
> Improve spawn regions on level map

- Source/Kesmai.WorldForge/Game/Screens/WorldGraphicsScreen.cs
Very simple fix for a bug I created on WorldForge with my previous update. Text for portals only showed when spawn regions were also turned on. I have just moved the text draw loop out of the area just for spawn regions.
> bug fix where text for portals only showed when spawns are on

- Segments/Oakvael.mapproj
The original comment in the code shows they expected the damage to be 60 per turn but actually that was per tick. 3 Ticks per turn, so damage was actually 180 per turn, enough to kill anyone if they didnt move instantly at the right turn (verified by Vics replay).
Level 7 will have expected output of damage is 28 per tick. 84 per turn, which is still high but potentially survivable.
(excluding melee damage taken by Wendy)..
Very rough chart of effect of blaming through a level 7 WW:
Very rough chart of effect of Double blaming through a level 7 WW:
> Setting a reasonable level for Wendy's WW

- Segments/Axe Glacier.mapproj
Changes to pwolf to spawn like kwolf does - the spawns were excessive all over axe per OG / Lands numbers. They'll still spawn everywhere, and Rockworms are still available, but this makes silver dagger / SGA not needed 3-5 times per Axe level. Follows OG much more closely where the possible kwolf spawns are also possible pwolf spawns.
Chilly's changes to axe UD mobs that needed to be refreshed due to Github resolves is included.
As are Yarrim's requests and Angry's revisions in this pull:
https://github.com/jkachhad/Stormhalter/pull/1518
> Pwolf randomization edit

- Segments/Leng.mapproj
Decreased scorpion poison by 2,
decreased nomad archers from Longbows to Shortbows. Level above has longbows. I feel it's much more appropriate as we've had lots of feedback about the archers.
We can decrease the total number if still a problem but I think this will make the area more attractive to hunting
Took bees and ravens from nomad as well and compensated with more nomads. I think with the decreased archer threat and the ability to pull into non-dense spawns this edit is also appropriate.
Those bee poisons stack.
Density is still .16 which is lower than other spawns. (need to look at density still)
> Nomad cliff balance

- Segments/Oakvael.mapproj
I actually like Wendy's whirlwind damage where it's at - it can be healed through.
Feedback is that there isn't enough threat on her with the once per minute cast.
I propose reduction of total mana to let her cast 3.33 times per minute.
Threatening but easily played through
> Wendy Update

- Segments/Underkingdom.mapproj
Yasnaki 3 pack of thaums curse went from 7->4 in the caster pull.
This makes them 15-17 damage, which as a 3 pack is 45-55 high end damage. It can also be broken apart. It was too much before, it's too little now. I propose a boost from 4 -> 5.
> Increasing damage on Yasnaki Thaums

- Segments/Axe Glacier.mapproj
* Upped the gem value to be "Slightly" higher than -3 gems 
-3 kesmai is based on Level 5 crits 
Axe Surface is based on Level 6 crits
> Normalize Axe Surface Gems with -3 gems. -3 is easier than axe surface

- Segments/Oakvael.mapproj
* Created a Mid Level Gem Tier
* Split level 3 crits to remain on Low Level and level 7 crits to Mid Level
Currently looking at the numbers -3 Kes uses a "General Kesmai" gems. These are level 5 crits. 
-2 Oak has level 7 crits yet still has lower gems for some odd reason
> Oak Gem Normalization for -2 to match Kes -3 (probably should be higher)

- Segments/Oakvael.mapproj
Keeper was unintendedly marked as chaotic instead of neutral. Quick fix.
Seems I forgot to open this one yesterday
> Small fix to quest entities alignment

- Segments/Leng.mapproj
Nothing Major. Bug fix for possible vlad not spawn + reasonable spawn time for vlad tower. Currently in HC each layer respawns in 5 mins!
Tower 1: Was 15-20 mins Now 2h30-3h
Tower 2: Was 15-20 mins Now 2h30-3h. Also changed Max spawns to 6 just because there are only 6 that are setup so 8 is impossible.
Tower 3: Was 15-20 mins Now 2h30-3h
Vlad: Was 3h-5h Now 3h-4h. Also changed max to 5 as otherwise there is a 1 in 4 chance Vlad would not spawn at all! 5 entities can spawn.
> [just bug fix] updating some spawn Max on Vlad

- Segments/Axe Glacier.mapproj
It looked like a gap you could go through but you cant and cant see through it. It just looks wrong. I changed the upright wall into a corner wall so displays correctly. No change in functionality
was
now
> fix gap in walls you cant go through

- Segments/Oakvael.mapproj
Turned grove from sloppy shield shape to actual heart shape
Evened out spawns with a <.20 density and 25-30 minute respawn (pre-adjustment)
Removed the random cat demons that prevented the zone from being particularly farmable.
Increased gems to be equivalent to axe undead - difficulty should be similar.
Revamped escort quest - just one cat demon resides in the aorta passage, killing it will despawn the obstacles and begin the escort but the escort is farther now. 
Upon finish of the escort quest a boss is released from behind the blocked pulmonary veins.
> Fixed grove heart

- Segments/Axe Glacier.mapproj
Was recently brought to attention that axe is using a nonstandard naming system. This has been fixed
> Axe Naming Convention Fix

- Segments/Kesmai.mapproj
1) he wasn't dying correctly I think this was due to his onDeath code creating and moving the item. I now specify more detail about the segment to move the item to.
2) the guardian correctly Wakes when you move on his square but then is loose if you flee or die. There is now a timer that waits 2 mins since he last cast a spell on someone (aka saw someone) after which he is reset / teleported back to his start position and make him not move again.
3) The code where I try to stop more than one player in the lair at once did not work so I'm trying a cleaner version where we check all players subregion.. if it matches the guardians lair then we refuse entry.
4) Also removing a test door I put in the Test area
> update for guardian test

- Segments/Kesmai.mapproj
This is a Very simple change to the test area for guardian. 
Needed a check for null on the sub region.
Thanks
> test guardian - needed a check for null

- Segments/Oakvael.mapproj
**Overall Goal:**
_Current difficulty:_
-1 oak  = -2 Kes
-2 oak =  between -3 and -4 Kes probably similar to Axe cave.
-3 serp = just harder than -4 kes 
-4 TT = slightly harder than serp
-5 UD is a lot harder than TT
_Im thinking....._
make -1 more useful .. about difficulty of axe cave/-3 kes
-2 very slightly harder (between new oak -1 and -3)
-3 leave
-4 make a little harder between serp and ud difficulty
-5 leave
**What I have done:**
I have tired to make -1 Oak more useful to players that could reach it. On par with Axe caves, but different due to different mobs.
I have deliberately left a path though that has a chance of slightly less density so as to try to reduce impact on Konran quest. basically the E and W spawns avoid this path (but do over see it) and there is a whole area …
> Oak -1 polish

- Segments/Oakvael.mapproj
so I had to re-do my -2 update! due to conflicts caused by the -1 update.
anyway.. I have also put in some tweaks to -1 after testing it. -1 had too many snakes and scorps at once, so fixed that. They and spiders also did too much poison damage for the difficulty so I tweaked that. I also slightly increased their exp as they drop nothing and have a higher risk factor due to poison so reward via slightly higher exp a bit like we do for archers and MUs. oh and I also tweaked the spawn areas so maybe less zoo as soon as you go down.
-2 I did same as before except I decided to tweak the spawn area to make it headier density in the East (north and south) leaving a slightly fairer route for Konran. I did also add in an extra secret door for 2 reasons.. I want to encourage going through that …
> Oak 2 and 1 tweak

- Segments/Blackburrow.mapproj
1st in a series of changes I plan on making based on some play throughs I've finished on my Non-twink knight. There's way too much gold for the difficulty, and there are some choke points with too many mobs. So I mean to address those issues in the next few changes. 
There are no new items, the most likely change to cause problems is the art I added. However, it should have already been compiled in. 
Made the following changes to Blackburrow:
- Lined up the stairs "vertically" so all the stairs and their location make logical sense with respect to the entire map
- Slowed the respawn rate by 5 minutes on all normal mobs
- Cut Gem drop rate in half on regular mobs
- Lowered drop chance of PP on lockjaw, removed Strong Shield bracer from miniboss loot table
- Added Dexterity ring to Dragon …
> Blackburrow Changes

- Segments/Underkingdom.mapproj
Carfel was accidently made easier due to MainGauche was added as part of his weapons. Carfel can no longer block properly due to it is a Neutral Dagger. Switching it to just drop the dagger versus use the dagger.
> Fix Carfel's block to not be bugged from MainGauche Alignment

- Segments/Underkingdom.mapproj
At this current time Carfel can not block a level 9 skill thief. Looking at the history, noticing that a change was made to dodge.
Reverting these changes in hopes to fix his block. Otherwise a level, 15/5th dan thief can kill him solo at this time with kosh gaunts.
> Carfel Difficulty - Change Back to Original State

- Segments/Leng.mapproj
- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Maces/UnholyScepter.cs
Currently this is the only way we have found out to make sure people don't carry a corpse with the item on it. This ensures the player has to attempt or at least traverse to the region to get the item. (similar to OL staff)
Leng: Killer Rabbit 
Bloodlands: The Queen
> Move Ram Staff and Unholy Scepter to Wield

- Segments/Leng.mapproj
Revert Change due to Lawful weapons don't work on Chaotic / Evil creatures. Correction 1 swing, looks like the jump kick did not trigger it.
> Evil / Chaotic can not wield lawful weapons

- Segments/Blackburrow.mapproj
Last time accidently instantiated spells in the collection as a single Object instead of a list of objects. Also no real need to have a separate entity in the Segment area, due to it's just going to be inheriting a combat UI. Blackburrow for now since it has the least traffic.
OLD: 
testTrap.Spells = new CreatureSpellCollection(50.0)
{
new CreatureSpell<ConcussionSpell>(
skillLevel: 3), 20, TimeSpan.FromSeconds(3)
};
NEW: 
testTrap.Spells = new CreatureSpellCollection(50.0)
{
{
new CreatureSpell<ConcussionSpell>(
skillLevel: 3), 20, TimeSpan.FromSeconds(3)
}
};
> Add Back Traps at the entity. No need to worry about Segment tab

- Segments/Underkingdom.mapproj
- OL Traps need night vision to see players or any other non aligned. 
- OL Traps will now cast 100.0 if their spell rotation is within the 5 seconds.
> Traps need night vision due to OL Hall is permadark. Also cast 100% if their spell is not on cool down.

- Segments/Axe Glacier.mapproj
1) Mama has always been able to attack 3 hexes away in other emulators. This is a fix since Charge only attacks 2x away. 
2) Due to CreatureSpellCollection(35.0) is at 35% spell to melee ratio and also a timespan is being applied for 15 seconds, the icestorm is far less frequent than any other version. Just to slightly affect db ice percentage bumping the rate up by 5 seconds.
> Adjusting Mama to be able to fly/hit 3x away. DB Ice is super infrequent currently. 

- Segments/Underkingdom.mapproj
The skill level is what matters here. The concs are basically killing off all crits and then some.  A user should be able to react. This should probably make them a wee harder from Magic Missile though, since conc is actually weaker.
> Yasnaki Wizards are casting 2 concs and then an icestorm when full mana 

- Source/Kesmai.Server/Game/Items/Miscellaneous/BrightFeather.cs
* Bright Feather Category for Baggable
* Adjust Drop Ratio Higher on Bright Feathers for Lower Bosses in Bloodlands so everything is not so dependent on DXing people up to Sky temple
* Fix Anubis by adding Poison Immunity as well as PC immunity
* Add actual Hide Detection for level 14-17 crits
* Feedback from Ekky - Scythe does not need speed adjustment. Removing.
> Fixes for Bloodlands and Baggable Bright Feather

- Segments/Leng.mapproj
Since Lux fixed the instant casting fizzles on mobs the cast rate on certain bosses feels a little high. 
Tweaking Kosh's DB fire from 4 out of 10 attacks down to 2. We can test it again and tweak back up if necessary.
> Kosh casting rate change

- Segments/Axe Glacier.mapproj
- Segments/Blackburrow.mapproj
- Segments/Oakvael.mapproj
Axe - Spectre had Mana reversed in props, so the mana would always be 0. 
Bloodlands/Blackburrow - Fear/Blind status on Bosses instead of immunity type of spell.
Oakvael - Complaints that the zone was over populated. Thinned it by 10 a quadrant to see if that helps. (40 less and the -10 more on the Gap Coverage)
> Various Bug Fixes for Fear/Stun/Blind and others

- Segments/Oakvael.mapproj
Grove Snakes only spawn in Grove
Currently if user recalls into another region, they can accidently kill another player. The region needs to be evaluated before the entity is spawned.
> Grove Snakes only spawn in Grove

- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Maces/UnholyScepter.cs
Bloodsword:
* Moved Item to twins down in the Forest
* Add 2 H to sword and also make it fumble if something is in left hand
Unholy Scepter
* Add CanUse to Scepter since it worked for Scythe. (Only Wizards / Thaums)
> Bloodlands can use and fumble calc to two weapons

- Segments/Underkingdom.mapproj
1) Add Spawn Teleports to all Mini / Notable / Major bosses that spawn in a region vs spawn location. Hopefully fixing a boss leashing issue we have seen.  (these are already on the majority of bosses)
2) Removal of Test Code for Speedy Hob (The other level 13 mob is still there). Removal of Princess Scroll since it is no longer used.
3) Add Panic to Princess if she gets hit.
4) Add new Generic Announcement for anything other than Bosses. Aka Princess.
5) Make Rares more rare vs actual Boss Crit Loot.
> UK Fixes - Add Iterative Fixes and Removal of Test Code

- Segments/Axe Glacier.mapproj
Giant
Since it is 100% - just drop at feet. No more corpse teleportation.
Ydnac
Add D3 roll for the removal of the group loot. (33.33%) Evaluate if lands on 3 and drop at feet, otherwise bail out. No more corpse teleportation.
> Both Rhammers drop on ground (similar to -4 Kes Rhammer) - Adventurers need to Adventure

- Segments/Underkingdom.mapproj
Keep SShielder rarer. Vlad already has a flat 6% drop. PP amulet has like 4 more percent higher than S/D.
OG Loot tables:
OL Staff 100%
PP Amulet 100%
S/D Amulet (not sure)
SShielder didn't exist
Lands Loot Table
OL Staff 100%
PP Amulet 100%
S/D Amulet was only in AG
SShielder didn't exist
> Overlord Loot table Reversion

- Source/Kesmai.WorldForge/Editor/MVP/Models/World/SegmentEntities.cs
* Ensure Entries are present prior to Save
* Only throw warning and do not bail out. This will ensure XML doesn't save in a bad state.
Added video in: 
https://discord.com/channels/577503035526348810/1085958474363580527/1089923618168918088
> WorldForge - Add Validation on Save for Region and Location Spawns

- Segments/Blackburrow.mapproj
Updated the Thief Lair of Blackburrow.
Changed damage values for lair minions.
Extended Thief lair with traps and shadowstepping encouragement.
Fixed 1 hex in Kesmai -5. Rubble is visible now.
> Thief Lair update tiny kesmai -5 change

- Segments/Leng.mapproj
Leng - Priest uses the location spawn, but there is a region spawn there too. Checked all other segments and this has no usage. Removing Spawn region now.
-- Proof Leng is already spawning Priest: 
Kesmai -1 - Library spawn is empty completely. Added a minimal amount of crits as fillers.
> Kesmai and Leng missing Entities

- Segments/Oakvael.mapproj
* Divide Spawn to be in quadrants and a courtyard spawn
* Adds more risk in courtyard, but keeps crits divided to keep the hunt moving.
* Add Scorpion Notable Bosses prior to Lich Twins as Lands has them.
* Increased difficulty includes a slightly higher gem mutator
* Lich twins will now cast twice properly before engaging in melee. (Lands implementation)
* Add proper Body ID for Wendy
> Oak UD Spawn Split and Wendy Body using proper body

- Segments/Oakvael.mapproj
https://discord.com/channels/577503035526348810/587249411772645406/1104158833846255628
* Noticed the crits only took two-three halberd swings. Adjusting the HP now.
* Re-adjusting the Mana back to 21 for the liches. 
(Both tested on other Emulator)
> Oak UD - Tone back down the new scorps and Up mana on liches for 3 casts

- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Swords/BlackSteelRapier.cs
- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Swords/Rapier.cs
Reset the Rapier base-class. (should probably avoid altering these.)
Moved nesc attributes to the Blackrapier, and boosted Brapiers defense to 3.
> Rapier Fix

- Source/Kesmai.Server/Game/World/Maps/Components/Ground/Web.cs
Proposed change to the Web.cs component to make web mechanics stronger against players. Currently most players in the mid 20's and higher are almost completely immune to all web effects. 
This would allow us to add more web effects as a mechanic, and give us a reason to introduce items that have web immunity to the toolkit.
> Increase effectiveness of web as a mechanic

- Source/Kesmai.Server/Game/Items/Equipment/Weapons/Daggers/Dagger.cs
Added a property to dagger base class that allows venom to be scaled across all daggers. Also implemented the multiplier by overriding the base OnHit method to check for poison on the dagger and modifier the potency with the multiplier if it's greater than 1. 
I put a setter on the property so we could make other wearable items that could have multipliers that further adjust the potency.
> Add poison multiplier to base dagger
