Segments/Kesmai.mapproj
Added starting point for Kesmai randomized jeweler.
"Mentally" compiled. Editor is not showing errors for simple syntax issues.
=> Kesmai shopkeepers

Segments/Axe Glacier.mapproj
Issues with Axe map:
Not sure on kwolf spawn.
Martial Artist - unsure of context. Maybe fine.
Rockworm = Sandwyrm?
Lizard spell syntax - copied salamander but not 100% on variables.
Giant = ElderTroll type atm. Stats wildly unsure
Goose = dog atm.
Drake = dragon model
Mama needs HeavySilver immunity variable needed to be added.
no Statue model available in menu.
No value for Vulcan.
No value for Silvermoon
Not sure on MA trainers.
No lockpick town spawns.
Treasure needs full rework.
=> Update Axe Glacier.mapproj

Segments/Axe Glacier.mapproj, Segments/Oakvael.mapproj
Added high level (Foote) Axe MA. Changed Thurgen to low level MA trainer.
=> Fix Axe MA trainers. Setup oakvale with entities, spawns, treasures.

Segments/Axe Glacier.mapproj, Segments/Kesmai.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Changed a few unimaginative and elementary block messages in a few spare minutes. 
Didn't want to have the Kesmai exp bump committed in this one but I couldn't see how to remove it.
=> Changed a few " Blocked " messages

Segments/Axe Glacier.mapproj, Segments/Kesmai.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Should be fairly accurate to OG now minus tweaks. Gem types need work but there's a stand in for the tourmaline bar. Boss loot needs work. Other stats will need tweaks.
=> Added shield pens, updated loot tables

Segments/Leng.mapproj
Portals on the surface and thieves guild should work now until we get specific item requirements ready to go / more easily set in the editor.
=> Portals to Stables / Shid

Segments/Kesmai.mapproj, Segments/Leng.mapproj, Segments/Underkingdom.mapproj
First attempt at spawning in Ydnac Secret. Lets see how it goes.
=> Trying to spawn Ydnac secret. 

Segments/Kesmai.mapproj, Segments/Leng.mapproj
Added parameters so things would actually spawn in the areas I intended. Thanks Sewer!
Also as a test I add a mummy spawn in leng south maus with instant cast curse ( max mana 3 so only 1 cast ). Just seeing if I am getting the hang of stuff or not.
=> Added parameters to spawns

Segments/Axe Glacier.mapproj, Segments/Kesmai.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Eyes bleeding, everything uniform. Hopefully no errors.
Apologies if it overwrites anyone elses changes it's a pretty global set of changes
=> Uniformity Changes

Segments/Underkingdom.mapproj
--Temp Fix: Changed portal behind TK from Item to Hidden
--HummingBirdGhost: Fix spawn location, Give 1hr Respawn, Add Cast Delay to WW and decrease damage, Decrease Health
--Fixed some OL Wraith Spawns
--Fixed some surface Lurker Spawns
--Fixed Recall Vendor
--Added Thieves Guild TP to stop non thieves from entering
--Added PP amulet, S/D Bracer and Purple robe to OL loot
--Adjusted Drakes 3rd Attack
=> Various UK Fixes

Segments/Axe Glacier.mapproj
Implements an example AI that scavenges for gold. Alia would pick up just gold in OG, but she will pick up any `ITreasure` and be happy for a few rounds before returning to scavenge again.
=> ScavengerAI

Segments/Bloodlands.mapproj, Segments/Kesmai.mapproj
fixed some counters and stairs issues also added more spawns..
Fish no longer walk on land!
=> Bloodlands fixes and enhancements

Segments/Kesmai.mapproj
Trial pass at tile consistency in Kesmai.
Changed the Granite Pillars to indestructible.
Changed floors to statics under indestructible walls and statics to floors under destructible walls.
Added ruins to a few destructible pillars and made portal spikes indestructible.
=> Kesmai walls

Segments/Bloodlands.mapproj
accidentally had priest spawning out of bounds
=> Bloodlands Fixed Priest Spawning and other enhancements/updates

Segments/Bloodlands.mapproj
fixed unicorn lair... aain
fixed boss 2 HP / spell
removed many archers on -100
fixed HPs on -200
=> Bloodlands Updates / Enhancements

Segments/Axe Glacier.mapproj, Segments/Oakvael.mapproj
-Added Byrch
-Added Gorffwylltra
-Added Halberd to Oak Dragon
-Updated Axe Yeti with Quest Progress Trigger
-Updated Wendy with Quest Progress Trigger
Send quest file via discord.
=> Second Knight Quest

Segments/Leng.mapproj
Updated Vlad Encounter:
*Gave Vlad Nightvision
*Added a Lich to his penthouse that drops SGA.
=> Updated Vlad Encounter

Segments/Axe Glacier.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Also increased some spawns in leng to correspond.
Massive decrease in damage on most monsters due to absolutely bonkers spawn increase rates.
Legit OG accurate though
=> UK Spawn increases to match OG.

Segments/Axe Glacier.mapproj, Segments/Blackburrow.mapproj
Created a new dungeon that will connect to the existing lands in the ogre caves in axe. I made the necessary changes to axe as well, although I didn't know how to link the teleporter. 
I have no populated spawns, but I wanted to be able to walk through it and see what needs to be changed.
=> New land (Blackburrow Mines) for testing

Segments/Oakvael.mapproj
- Changed Byrch min/max spawn number to 1.
=> Added Spawn for Byrch - Oakvael

Segments/Axe Glacier.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Also trainer quality of life improvements
=> Axe Undead

Segments/Axe Glacier.mapproj
Less frosties, hopefully they cast spells, slightly more spawns with worgs.
=> Axe Undead balance changes

Segments/Axe Glacier.mapproj
- Added exit teleport in Silvermoon's area
- Added locker to Lockpick Town
=> Silvermoon exit and Locker for Lpick Town

Segments/Oakvael.mapproj
- Added exit teleporter to reptile pit.
=> Oakvael_ReptilePit_Exit

Segments/Kesmai.mapproj
- Added additional teleport to second hex for HoL to allow use with feather.
=> Kesmai - Additional HoL Teleport

Segments/Blackburrow.mapproj
Some quick changes, to make the map more playable than it was Day 1. Since you are currently unable to explore the map due to broken stairs.  Thanks for the help to everyone who's guiding me along. 
Fixed the following:
- Pulled NPC's out of the walls in town
- Removed all static tiles 
- Fixed the entrance level stairs
- corrected mob names
- Corrected Vendor counter tops
- Made the casters in the Blacksmith area a little harder since Darkice was one shotting them. 
Added the following:
- Changed the southwest corner of the level 1 dungeon into a prison
- added prisoner mobs that beg for help when the player enters into sight
- populated the level 1 dungeon with mobs of varying difficulty
=> Updated Blackburrow to V2

Segments/Axe Glacier.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Populated shops in Leng, Axe, Oak and UK.
Each vendor picks a few items from a common stock per vendor class, and then gets a chance of a few rare items.
Leng has a fun new vendor. Go visit Gill, East of the balm and recall vendors and try your luck.
Added the default vendor messages to each land.
=> Vendors in Leng, Axe, Oak, UK

Segments/Kesmai.mapproj
- Replicated static teleport comp in kes lockers.
=> Kesmai - Adding Static Comp to Teleport

Segments/Bloodlands.mapproj
- Adjusting Restels position out of the wall
=> Bloodlands - Moving Restel

Segments/Oakvael.mapproj
- Fixed teleporter in Reptile Pit's target
=> Oakvael Reptile Pit Fix

Segments/Underkingdom.mapproj
- Lowered UK Princess' desire for blood and gore.
- Added trail option to princess.
=> UK - Princess Set to Passive and added trail

Segments/Oakvael.mapproj
- Added Silver weakness to gargoyle to match previous iterations.
=> Oakvael - Garg Weakness Update

Segments/Axe Glacier.mapproj, Segments/Oakvael.mapproj
Please do not commit this branch without adding the OakGroveBow to itemization (and including new serializations for entered text
[OakGroveBow.txt](https://github.com/jkachhad/Stormhalter/files/7190886/OakGroveBow.txt)
s)
=> Big grove addition

Segments/Oakvael.mapproj
Added the removecomponent script (might need edits)
Added the AI addition to the necrotrophs to OnLoad since that's what's in the snake.cs and it works for them.
=> Grove branch

Segments/Axe Glacier.mapproj, Segments/Underkingdom.mapproj
*important*
Not sure what the descends changes are. I didnt do anything to tiles.
=> Changes to lockpick town

Segments/Oakvael.mapproj
Grove patch notes:
Grove keeper is mortal when changes to green and must be guarded for the quest. This fixes an easy experience exploit that's been noticed :p
Slight balance to gems / gold / experience.
Teleport exits added to the rooms that can be locked.
=> Grove changes

Segments/Oakvael.mapproj
Fixes jkachhad/Stormhalter#1032
=> Oak Grove - Bear Spirit Tether

Segments/Underkingdom.mapproj
A few secret door fixes. -280, yasnaki, lightning caves
=> A few UK Secret Door fixes

Segments/Oakvael.mapproj
- Moved Recall Ring vendor to the correct hex
- Moved Low MA trainer to correct Hex
=> Oakvael Updating NPC Positions

Segments/Blackburrow.mapproj
Set Blackburrow counter accessDirection to South instead of North.
Some people will be enthusiastic about this... probably.
=> Blackburrow counter accessdirection fix

Segments/Axe Glacier.mapproj
Pushed experience changes for axe undead to even out with grove experience values.
=> Axe Undead updates

Segments/Axe Glacier.mapproj
- Updated spawners to spawn NPCs in the Axe Pub.
=> Axe Pub Population

Segments/Blackburrow.mapproj
- Removed prone from regular mobs
- Reduced the number of prone attacks from bosses
=> Blackburrow Prone Removal/Reduction

Segments/Axe Glacier.mapproj
Created spawn and used existing (but previously unused) entity.
=> Spawn for thief trainer in Axe

Segments/Axe Glacier.mapproj
Something with the custom code for Draugr and Frost giants were interfering with caster AI - Not sure if it needs looking into, but generic mages and archers are in. People will appreciate the variety in monster model / naming too. Wusses :P
=> Changes to casters/archers

Segments/Underkingdom.mapproj
Added an item for princess quest to be turned in to start quest - essentially a key style item.
Edited gems to be more like OG UK.
=> Uk pending issues

Segments/Leng.mapproj
Fixes #1200 
May need to consider other areas to mark.
=> Mark leng priest area with town subregion

Source/Kesmai.Server/Game/Items/Equipment/Rings/Strength/WeakStrengthRing.cs
Fix weak strength bonus from 3->1
=> Fix weak strength bonus from 3->1 (Address issue #725)

Segments/Leng.mapproj
Was able to get rid of all those pesky commits. Also Added back Leng Bridge Troll to charge + Comment
=> Add Can Charge to Leng Bridge Troll

Segments/Kesmai.mapproj
- Moved Rgem drop outside of quest loop to allow item to be obtained outside of quest state.
=> Kesmai Rgem Update

Source/Kesmai.WorldForge/Editor/TerrainManager.cs
No net effect until there are external art assets in the BIN files.
=> Support for upcoming External terrain definitions

Source/Kesmai.WorldForge/UI/Documents/EntitiesDocument.xaml
I had excluded this change from a previous commit, but it crept in in a later one. This is unfinished and nonfunctional. Removing.
=> Reverting unintentional change to Entities

Segments/Oakvael.mapproj
Sorted out potions, treasures, gems, gold, wands, balls.
Set in motion new changes in scaling to Grove monsters. - Beginning of Grove should be level 16 monsters (UK yasnaki is 15 for reference), later grove should be 18.
Removed alignment changes from Grove monsters.
=> Long Pending Changes

Segments/Leng.mapproj, Source/Kesmai.Server/Game/Items/Equipment/Gauntlets/KoshGauntlets.cs
*Added Blue Glow to +2 gauntlets and placed them on Kosh
=> Leng - Kosh Gauntlets Added

Source/Kesmai.WorldForge/Editor/MVP/Presenters/ApplicationPresenter.cs, Source/Kesmai.WorldForge/UI/Panels/ComponentsPanel.xaml.cs
Added a check to prevent duplicate object names. Also now catching Exceptions during the saving process instead of crashing WF without a chance to fix them.
=> World Forge 2/1

Segments/Leng.mapproj
* Removed Crit from Power Troll
=> Leng Removed Crit from PowerTroll

Segments/Leng.mapproj
*Added Swim to PowerTroll
*Added WB to PowerTroll
=> Leng - Added WB and Swim to PowerTroll

Segments/Axe Glacier.mapproj, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Dragonkin/IceDragon.cs
Gems are sparse, will be adjusted up once gold per monster is discussed.
Monsters have been changed slightly - the vast majority making them less dangerous.
Giant will hit more often now but for less - he can critical strike now though so be careful.
Treasure such as youth pots have been increased.
Don't trust the yellow liquid.
=> Axe revision

Segments/Blackburrow.mapproj
*Removing weapon so it compiles
=> Blackburrow - Removing Weapon

Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Apatosaur.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Bat.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Bear.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Dog.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Duck.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Fish.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Frog.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Goose.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Hippopotamus.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Lizard.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Lurker.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Manticora.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Panda.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Piranha.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Sabertooth.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/SeaSerpent.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Serpent.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Snake.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Wyrm.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Humanoids/Humanoid.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Magical/WaterElemental.cs
Swim / Breath water edits for humanoids and a bunch of monsters.
=> Mostly swim edits

Content/Content.Stormhalter-External.mgcb, Content/Data/Terrain-External.xml, Content/WorldForge/Components.xml
More wall art from Tenser, and an animated campfire*!
*Campfire not animated in screenshot
=> Art doodads

Segments/Leng.mapproj
=> Leng Kosh Gaunts

Segments/Blackburrow.mapproj
- Made the Dragon vulnerable to Blue Glow weapons
- Moved to entrance of the thief lair
- Added the Main Gauche thief blocking weapon
- Made the pit a little easier to escape
- Made the roaming see-hide archers move slower. 
- Fixed some assorted spawn issues.
=> BlackBurrow Changes

Segments/Axe Glacier.mapproj
Trying to get compiler to recognize new constructor for Moon Stone Ring.
=> Add Source Code for Moon Stone Ring and add TypeAlias. Remove partial

Segments/Axe Glacier.mapproj
=> Syntax issue

Segments/Axe Glacier.mapproj, Source/Kesmai.Server/Game/Items/Equipment/Rings/MoonstoneRing.cs
Copy and pasting a Quote causes issues
=> Copy and pasting a Quote causes issues

Segments/Axe Glacier.mapproj
* Added Moonstone ring drop to Giant
=> Axe - Added Moonstone Ring to Giant

Source/Kesmai.Server/Game/Items/Equipment/Weapons/Axes/Axe.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Axes/BattleAxe.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Bows/FineCrossbow.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Halberds/Halberd.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Maces/Mace.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Staves/Staff.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Swords/Sword.cs
Added shield pen to all weapon classes. Can revise from light to very light later
=> Shield pens

Segments/Underkingdom.mapproj
The white wyverns can still be killed by drake.
=> add immunity to lightning for white wyverns

Segments/Kesmai.mapproj
* Bumped Sherriff attack so he can deal with big bear if bear is pulled to town.
=> Kesmai_Updating_Sherrif

Segments/Kesmai.mapproj
* Prevented portals into thief lair in Kesmai.
=> Kesmai - Made wall indestructible

Segments/Axe Glacier.mapproj, Segments/Kesmai.mapproj
Daisy lair (no-recall) now extends to cover the altar room East of her.
Moonstone Rings are now required to enter Silvermoon or Vulcan's forges. Hold the rings during the night to gain entry.
=> Moonstone Ring portal & Kesmai Dragon lair

Segments/Underkingdom.mapproj
… it back to town
Hummingbird sword fix. So people can't twink all their characters by dropping corpse. This could have been fixed with the No recall zone inclusion too.
=> UK - Create Guardian Lair (no recall) and Make it so Guardian Drops weapon off Boss, instead of body.

Segments/Underkingdom.mapproj
* Since we have no recall zone, not really worried about this anymore. 
* This will make it so Guardian has hummer as part of loot again
=> Reverting Guardian Change

Segments/Axe Glacier.mapproj
Added Rstaff for Wizards per conversation with Lux. Intended to be a ranged staff option for wizards/thaums that blocks less than an OL.
=> Wizard and Thaum wand

Segments/Kesmai.mapproj
* Updated tile from floor to water so it behaves as presents.
=> Changed tile to be water as expected

Segments/Underkingdom.mapproj
* Min timer was over max timer, adjusted both to 1 hour.
=> Updating Princess Timer

Segments/Oakvael.mapproj
Removed artifact segment code
Grove Heart monsters will now all be evil
=> Grove Fixes

Segments/Axe Glacier.mapproj
Bears could see in dark. Been meaning to put this in.
=> Axe Bears should see in dark

Source/Kesmai.Server/Game/Entities/Mobiles/MobileEntity.cs
Allow for armorBonus to mitigate damage right away.
This will provide a lot of mitigation vs packs of monsters (and archers!).
=> DamageMitigation

Source/Kesmai.Server/Game/Entities/Mobiles/MobileEntity.cs, Source/Kesmai.Server/Game/Items/Equipment/Armors/Armor.cs
Should fix weapons with multiple flags seeing stacked armor. Highly recommend this gets tested on a local build first. Addresses issue  #739 halberds trigger extra defenses on target
=> WeaponFlagFix

Segments/Axe Glacier.mapproj
=> Fix Giant to be immune to concussion

Segments/Axe Glacier.mapproj
* A new mini boss in chaos town to parody some of the old stuff. 
* Water Breathing Bracelet 50% || Medium Shield Bracelet
* Magic Missile tuned up a bit
=> Water elemental, what could go wrong?

Segments/Underkingdom.mapproj
fixed destroyed secret door direction.  added destroyed nw corner art.  fixed floor tiles under destroyed walls and on some corners that were incorrect
=> UK destroyed walls fixes

Segments/Underkingdom.mapproj
EDIT:
Added additional places that sewer pointed out
Fair enough, I extended coverage, except I didn't violate the sanctity of the npc areas.  Lux mentioned making some improvements in the creature ranging.
Orig:
Adjusted -300 with gargs to help alleviate scripting
Adjusted sewers with night vision archers to help alleviate scripting
Additional mummies to remove safe zones for sniping
Additional troll guards and extended range to eliminate safe zones
Extended SM range to traditional range
Extended lurker range on surface to reduce sniping
=> UK Safe Scripting Locations Update

Segments/Axe Glacier.mapproj
I noticed that Mama isn't doing critical damage. Which makes her way easier than TK right now, which is why everyone is running around with icies right now. 
Let me know what you think, wasn't sure if we needed to tone her damage down a little bit to compensate... but I think she does need to crit shot.
=> Added a new “critical style” attack for mama, changed her to IceDragon class and removed icies from her loot. 

Segments/Oakvael.mapproj
Added nv to orcs in -2
Reduced exclusion zones for better coverage in serp
Reduced exclusion zones for better coverage in grove
reduced exclusion zones for better coverage in UD
=> Location safety changes in Oak to help alleviate scripting

Segments/Underkingdom.mapproj
Noticed some breakable UK walls with static components under them, fixed
=> Fixed floorless sections

Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Animals/Lurker.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Humanoids/Ogre.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Humanoids/TrollGuard.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Undead/Mummy.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Undead/Overlord.cs
Fix sound for Lurker, overloard, troll guards, mummies, and ogre
=> SoundFixes

Segments/Underkingdom.mapproj
Very simple change, I just removed the lurker magic immunity, I don't believe it's necessary, just having the small amount of risk is sufficient - no need for an epic fight.
=> -300 Lurker magic immunity removed.

Segments/Underkingdom.mapproj
also fixed random static water in sewers
=> Add floor to uk gym

Segments/Underkingdom.mapproj
* currently conc DJs can literally eternally stun him / kill him.
=> Fix Lair Bosses in UK to have concussion resist

Segments/Axe Glacier.mapproj
centered the lairs on their horde before the announce, can remove if we want it random
=> Add the rumble to axe

Segments/Axe Glacier.mapproj
This square near lock pick town, when turned to rubble, you could stand on it and no creatures would would you there.
There was 1 part destructible and 1 part indestructible which may have confused it so I have made it so both parts are indestructible.
=> exploit square - nothing came here

Segments/Leng.mapproj
sea serpent was set to not spawn. 
Should hopefully spawn now.
=> spawn sea serpent

Segments/Leng.mapproj
1) 3 wall components are no longer indestructible
2) Upped the difficulty only a little. 
3) Wall has been pushed up and Black knight and Enchanter spawns are in the same area
=> Let the thunder dome convene - Adding small tweaks to movie sequence. 

Source/Kesmai.Server/Game/Items/Equipment/Amulets/FireIceProtectionAmulet.cs
Currently it's blank so it does not even have a description. When identified it just says 3 of 3.
=> Add Description for Fire and Ice Amulet

Segments/Underkingdom.mapproj
This is a slight mix between what originally happened and what happened in lands. I can't be sure all of these mechanics will work as expected as they haven't been done like this before so it will need testing and possibly revising but I can't test it without putting it live.. and currently hummers are just free with conc bottles so this should be a good improvement. 
IMO this is a battle someone that has duoed TK should be able to solo (as its only soloable) so shouldnt be "that" hard. Just a check you are not a low level.
I believe I have managed to make it so only one person can enter the room at once. You then have to enter the centre of the room and defeat the guardian who throws WWs and hits you to check your fortitude.
This is what I changed:
1) removed normal portal hex
2) …
=> Hummingbird sword quest

Segments/Axe Glacier.mapproj
Kwolf spawner was replaced with pwolves.
Adding him back to his spawner so he can spawn again.
=> Kwolf spawner issue

Segments/Axe Glacier.mapproj, Segments/Kesmai.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Will go back and clean up NPCs later to remove individual immunities
=> Added immunity to base vendor model

Segments/Leng.mapproj
The autocrat himself found a tool that is very useful and hoards it in his tower. It can transmute minerals into large amounts of gold.
=> Vlad has a ring

Segments/Blackburrow.mapproj
Stage 1 of my revamp of Blackburrow:
In this update, I took @SewerCzar's table and aligned mob combat skills and difficulty with Level 12-16 depending on the area of the zone
Stage 2 will be fixing the loot.
=> Blackburrow Revamp Stage 1 (Align Mob Table with Level System)

Segments/Blackburrow.mapproj
Fixing an Oops that Chilly caught
=> Correction to Damage argument

Segments/Axe Glacier.mapproj
Found a big oops that was keeping him from spawning.
=> Fixing thief trainer

Segments/Underkingdom.mapproj
TK guards had a gap in the spawn causing them to pile up in his room if people were only doing princess. This fixes gap.
=> Troll king guards quick update

Segments/Leng.mapproj
=> Fix Queen Visibility - Add WB to Prin - Change Potion to Willpower

Segments/Annwn.mapproj
* Make all walls indestructible
* Add Segment
* Add Entities (including evil wizard)
* Add Location Spawns 
* Add Sub Regions for Floors 3 / 4
=> Annwyn - First Pass at Populating Evil Wizard Tower

Segments/Kesmai.mapproj
Adding a new Test Region currently with nothing in it, with the intention of trying new features in a more controlled environment before putting them live. It won't stop compile errors but if someone wants to try some new code and check it works before.. say, breaking the hummer portal, they could test it here first.
Each test could be put through as a separate commit so easy to just roll back to this empty state.
Initially (if this is approved) I would like to add a test in there for implementing the hummer portal correctly and also try some code to check there is only one person in an area at once. I will add that code on a separate request after this one.
You portal in from here in Kes:
The empty test area ready to have new stuff to test:
=> Adding a new Test Region

Source/Kesmai.Server/Game/Items/Equipment/Weapons/Axes/SilverGreatAxe.cs
Fix sga label and make it's category match the art category.
=> Change silver greataxe from axe to greataxe

Segments/Kesmai.mapproj
* Add a new region and add Midgit's map to this. 
* Not populated - and no way to access the area quite yet.
=> Add Midgits work to Kes

Segments/Underkingdom.mapproj
Similar to before. Key that is baggable -> hex next to princess -> door opens.
=> Updated Princess Quest

Segments/Kesmai.mapproj
This is all Test code and going in the new Test area in Kes. Its stuff I want to test for the to new hummer guardian stuff before I put it Live..
* need to hold a Balm in hand (will be amulet) in hand to enter. The Balm should vanish on enter.
* in theory only one person will be able to get inside at once (testing) - although there is a secret door for testing too
* the guardian fight is as i think it should be.. but currently drops a rHammer.. this is because I dont want to drop a hummer but I want to test auto binding a bound weapon to the killer.. so im using a rhammer as a basic item to test with
Test Portal:
Test fight area:
Im also throwing in a test for an idea to make decals not float when you open/destroy a door..
=> Test for hummer quest

Segments/Kesmai.mapproj
* Get Slysters UD up to date and merge all changes retroactively.
* Fix -5 stairs to face other way, component issue.
=> Merge Slysters UD

Segments/Leng.mapproj
There are various holes is spawn areas that cause mobs to get Stuck in 1 area unable to move around as intended. There were also some safe spots where mobs would never move. Note: Only Spawn areas are tweaked - nothing else
I have tried to make it so at worse there is never more than 2 spaces away from a spawn on appropriate areas.
I will detail the changes bellow: Long post but trying to make it visually very easy to approve.
**Maus**
From:
To:
From:
To:
From:
To:
From: **Important one - mobs got stuck in the crypt and couldn't get out**
To:
From: This allows movement through the whole crypt area
To:
From:
To:
**Shid**
From:
To:
From: **important - mobs got stuck in SW room unable to roam until disturbed**
To:
**undead** note: NW spawn was fine but NE and S spawns were very odd and not …
=> leng - fixing holes in spawn area

Segments/Kesmai.mapproj
Few map tweaks and removed the visibility modifier from the mummies as they were making it difficult on thieves to hunt the area.
Added some torches around the level but unsure how they will feel in game. Can be removed at a later time if they feel out of place.
=> Small Kes UD Update

Segments/Underkingdom.mapproj
UK Guardian Changes by Drak
* Portal consumes Hummingbird amulet
* Guardian is a fight. Completely spell immune. 
* WW has been decreased in damage
=> Hummingbird portal guardian changes by Drak

Segments/Blackburrow.mapproj
1) Switched around the Trainer code to spawn -> location. 
2) Use only two counters similar to Kesmai.
=> Fix Blackburrow Thaum Trainer

Segments/Kesmai.mapproj
added NightVision to my kesmai -5 creatures
added higher timer to huemongus
darkened the zone. Will darken it further later.
changed the northwest PORTAL to hopefully teleport the player to BLOODLANDS
fixed the reason why my second blood ghoul was not spawning.
added Teleports to push players away from the EMONDEUS gates.
Will balance WRAITHS and LOOT in future update.
Chilly
Went back and balanced skeletons and their loot. 
Add Demon body to Demon (masked as a Dragon)
=> Update Kesmai -5

Segments/Axe Glacier.mapproj
* A few people have come back to balm vendor being swarmed with Crits and have died. Preventing this from a recall stand point. 
SANCTUARRRRRY
=> Axe - Add New Statue to Protect those from going afk at recall/balm

Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Demons/Demon.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Demons/SummonedDemon.cs
* baseline for Summon Demon 
Up to @jkachhad - but hopefully this is enough to get started for Thaums.
=> Add baseline to summon demon

Segments/Underkingdom.mapproj
* Increase Wyvern difficulty a bit more
* Attempt at Speedy Hobs
* Balance just those two areas (Speedy and Surface)
=> Underkingdom Updates

Segments/Axe Glacier.mapproj
=> Fix Resists on Axe Bosses

Source/Kesmai.Server/Game/Items/Equipment/Weapons/Daggers/GiltDagger.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Daggers/YasnakiDagger.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Flails/SpikedFlail.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Flails/WoodenFlail.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Maces/WarHammer.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Swords/BlackSteelRapier.cs, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Swords/Rapier.cs
Give other weapon paths a shot.
=> Add New Weapon Values for Progression

Source/Kesmai.Server/Game/Items/Equipment/Amulets/Stun and Death/GoldenTorc.cs, Source/Kesmai.Server/Game/Items/Equipment/Amulets/Stun and Death/HummingbirdAmulet.cs, Source/Kesmai.Server/Game/Items/Equipment/Amulets/Stun and Death/IvoryBrooch.cs
Fix charges on S/D items to Represent OG
=> Fix charges on S/D items to Represent OG

Segments/Underkingdom.mapproj
Overlord fixes based on feedback from a variety of players.
Upped minimum damage from < half of maximum to ~2/3rds of maximum damage.
Turned on critical strike to be in tune with other major bosses.
Swapped charge to jumpkick to presumably enable target swapping to work.
=> Overlord Changes - Make more difficult.

Segments/Leng.mapproj
=> fix leng wolves

Segments/Axe Glacier.mapproj
Fix for yeti typo: smashing you with 5 fist
=> Axe Glacier - Yeti - Fixed '5 Fist' Typo

Segments/Blackburrow.mapproj
"Beware, the way ahead _if_ fraught with perils you can't imagine!"
^-- changed 'if' to 'is'
=> Blackburrow - Ghost of Darkice - Fixed Typo

Segments/Annwn.mapproj
All Vendors / Trainers.
Since we don't have all the other parts of AG, I can't add BWolf Quest vendor/Elk Vest or Special Weapon Crafter.
=> Add Town Population for Annwn

Content/Data/Items-External.xml, Content/Localization/Enu.xml, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Maces/UnholyScepter.cs
Add Scepter to Class Files For Bloodlands
=> Add Scepter to Class Files For Bloodlands

Segments/Oakvael.mapproj
Oakvael UD - Add same drop rates for Undead as UK Undead.
Submitted request by Stormhalter member.
=> Oakvael UD - Add same drop rates for Undead as UK Undead

Segments/Leng.mapproj
Previously you could tease out the black knight out of sight. Now you have to fight on the same screen. This will be an anxious fight, especially if someone tries to knock out the Jim first.
=> Leng: Jim and Blackknight have to be fought on the same screen

Source/Kesmai.Server/Game/Items/Consumables/Bottles/FalconStaminaPotion.cs, Source/Kesmai.Server/Game/Items/Consumables/Bottles/Temporary/TemporaryBullStrengthPotion.cs, Source/Kesmai.Server/Game/Items/Consumables/Bottles/Temporary/TemporaryStrengthPotion.cs
Dr.Taylor (Not Lloyd) with Cure Blind potions.
Added Bull and Falcon potions. (localization entry 375-376, after Bloodlands potions) Fixed the description of yellow temp str to include 'red liquid'.
=> Potion Stuff!

Source/Kesmai.Server/Game/Items/Equipment/Weapons/Daggers/Dagger.cs
Just an idea I'm throwing out there since daggers are "fast" weapons, and it's a way of boosting thief damage a little without making the weapons crazy. 
It's just an idea.. i don't know how this would effect mobs using daggers, etc
=> Dagger idea

Source/Kesmai.Server/Game/Items/Equipment/Weapons/Maces/ChaoticReturningHammer.cs
Fix Description due to bump up for Chaotic Hammer
=> Fix Description due to bump up for Chaotic Hammer

Segments/Annwn.mapproj
=> Annwn Fix Up Outer Containment walls and important walls

Segments/Oakvael.mapproj
Axe UD:
Drop Rate from Crits: 
new LootPackEntry(true, UndeadGems,       4.5,     gemsPriceMutatorAboveAverage), 
Grove Heart:
Drop Rate from Crits: 
new LootPackEntry(true, oakHeartGems, 4.5, gemsPriceMutatorAboveAverage),
=> Align Grove Heart Treasure with Axe UD treasure

Segments/Blackburrow.mapproj
* Black Burrow Gem TOwn
* Populate
* Add Gemini Town
=> Blackburrow update - Gemini Town (#1)

Segments/Blackburrow.mapproj
* GemTown Fixes
- Add Old Doors, due to Tori Doesn't work
- Fix EXP
- Fix Skels to be removed
- Fix Area floors
- Fix NPCs
* Update Blackburrow.mapproj
Missed a fix
* Update Blackburrow.mapproj
Remove some immunities
* Update Blackburrow.mapproj
More bashing immunity removal
=> GemTown Fixes (#2)

Segments/Blackburrow.mapproj
slight changes to surface
New areas in -100
New mines to explore in -200
Darkened both -100 and -200.
added more mobs to fight.
=> MidgitBlackBurrowUpdate

Segments/Blackburrow.mapproj
At the request of Lux, removing some of the cheese I added.
=> Remove Ghost of Memp and Darkice

Segments/Blackburrow.mapproj
changes to -300 and The Pit
new rope areas
new lair
=> BBchanges2Feb10th

Content/Localization/Enu.xml, Segments/Blackburrow.mapproj
Wizard Hat item add, same as before. I made so many changes it was confusing, so I closed the old PR and made this one to start fresh. 
To the best of my knowledge, this is ready to go now.
=> Wizard Hat -- BB - Clean PR

Segments/Blackburrow.mapproj
fixed some inaccessible areas.
fixed grates
swapped some BODY IDs
edited -200 access to the South Mines.
Upped HP on minor bosses
Upped Undead's poison from 3 to 6.
More mobs in -300
Changed some poison tiles in the PIT
=> MinorBBupdate

Content/Localization/Enu.xml, Segments/Blackburrow.mapproj
Working with Chilly to make changes based on compile errors. 
@jkachhad Still looking for some input/review.
=> Wizard hat  bb   compile error changes

Segments/Blackburrow.mapproj
Still learning this fork business. Hopefully only Kesmai -5 items are located on this pull.
+secret doors
+ambusher spiders.
+ new home for spiders
+ skill level of Soul sucker is 20 now.
=> Kesmai5secretdoors

Segments/Blackburrow.mapproj
Added Lightning resist to most Gnolls in BB
added DARKNESS tiles to STATIC darkness tiles in Kesmai -5 and Blackburrow town exit tunnel.
added lair subregions to a few areas in Blackburrow.
Fixed a wonky Secret door in Blackburrow.
=> LightningLairs

Segments/Leng.mapproj
CGS Fix - Hopefully Quest works all the way through
=> CGS Fix - Hopefully Quest works all the way through

Segments/Axe Glacier.mapproj, Segments/Oakvael.mapproj
* Level 19 Restricted Areas for Post UK areas
* Fix Spectre Spell - Icestorm was set to high.
=> Level restricted areas bg feature parity and fix spell on crit

Segments/Axe Glacier.mapproj, Segments/Oakvael.mapproj
* Bloodlands has bosses completely vulnerable to magic at implementation
* HP bug was on Sek
* Portal to 17 on Axe / Oak (only going in) with a potential portal to use it like stairs
=> Bloodlands Boss Immunity Fixes and Portal Oak and Axe

Segments/Blackburrow.mapproj
Based on community feedback I have removed lightning immunity and added lightning resistance to the gnolls on -100/200. We can continue to tweak these properties as necessary until it feels right.
=> Lightning resist tweaks

Segments/Leng.mapproj
=> Leng Altar Fix

Segments/Oakvael.mapproj
Fix for exit at thaum altar in Oak
=> Oakvael Altar Fix

Content/Content.Stormhalter-External.mgcb, Content/Data/Terrain-External.xml, Content/WorldForge/Components.xml
Cleans Terrain and Components of removed texture remnants. 
Adds a lighting and Shade category to WF
=> Terrain Cleanup

Content/Localization/Enu.xml, Segments/Leng.mapproj
* Tell users to go to Yuri if they haven't started the Quest
* Add actual text for missing Enu Strings
=> Fix Language for Puck and Update Enu

Segments/Blackburrow.mapproj
Addressing consistency in the attacks and blocks messages and naming of crits/mobs.
=> Consistency in Attacks/Blocks

Segments/Underkingdom.mapproj
* Elite Trolls in TK
* -100/-200 crits
* orc cave crits
=> Tether UK Crits that have no secret room/door

Segments/Axe Glacier.mapproj, Segments/Leng.mapproj
Yeti Dagger - Ram Staff
* prevent from corpse teleportation.
* code was already tested with hummingbird guardian. (see its entity)
* do not bind until user picks up
=> Move Weapons to Target Locations

Segments/Axe Glacier.mapproj
Some grammar, and other small typo fixes.
=> Axe Glacier: Fixing Typos

Segments/Blackburrow.mapproj
Addressing consistency in names of creatures, some grammar, fixed extra period showing up in "blocked by" messages, and other small typo fixes.
=> Blackburrow: Blocks/Attacks/Names Grammar & Typo Fixes

Segments/Annwn.mapproj
=> Fix Compile Issues on Annwn

Segments/Underkingdom.mapproj
Addressing consistency in names of creatures, some grammar, and other small typo fixes.
=> UK: Grammar, Naming, and Typos

Segments/Leng.mapproj
Addressing consistency in names of creatures, some grammar, and other small typo fixes.
=> Leng: Grammar, Naming, and Typos

Segments/Blackburrow.mapproj
added art for the Bloodlands Portals in Kesmai and BlackBurrow.
The static title should make them look red.
=> RedPortals for Kesmai and BB

Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Phantasm/SummonedEfreet.cs
=> Fix for DB Fire on Hex for Efreets

Segments/Axe Glacier.mapproj
=> Allia Fix for Raxe Drop

Segments/Blackburrow.mapproj
Change Some Entity Naming
added 3 new Gnoll Variants
Conc Gnoll (sooth variant)
Stalker Gnoll (stalker variant)
Thief Gnoll (yes hes skellyish)
Added them throughout -200 -300 and Pit and cut some Sooth spawns and raider spawns.
Edited Potion Master Nook's Spells
Edited a Spawning location
=> NewBlackBurrowMonsters

Segments/Underkingdom.mapproj
=> Poison Proof Shelob

Segments/Axe Glacier.mapproj, Segments/Blackburrow.mapproj
Axe Glacier: 1 hex near mama fixed.
BB: Entities names changed.
New Town Guard
additional dirt paths on surface
New Blacksmith area in -100
Worg Nerfed.
Added a gem to all minibosses.
added invisible WW to Thief Lair
added NV to Thief boss and poison
=> BB Organized

Segments/Blackburrow.mapproj
intensity is now 100 on Worg pup and Worg
=> worg minor fix

Content/Localization/Enu.xml, Source/Kesmai.Server/Game/Items/Equipment/Shields/SwiftShield.cs
Main issue is to update the Enum of shield to be not colliding with the Rules of Conduct Enum.
=> Localization Entry Update

Segments/Axe Glacier.mapproj, Segments/Oakvael.mapproj
* All Portals Removed
* Stairs Added Back
* Region Height Adjusted
=> Axe / Grove Stair Reversion

Segments/Axe Glacier.mapproj, Segments/Leng.mapproj
* Yeti/Rhammers back to corpses
* Raxe will appear on Allia if she steals it
=> Bg weapons move back to corpse

Segments/Axe Glacier.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Per request:
Dropped Archer pen down a notch in Axe, Oak, Leng, and UK.
Leaving BL, and BB for their makers as they're still a WiP.
=> ArcherTune

Segments/Leng.mapproj, Source/Kesmai.Server/Game/Items/Equipment/Weapons/Staves/RamStaff.cs
* Kosh now has a non inherited body 
* Crits are now split from one BIG ole rectangle to now have N W E. 
* Ram Staff now has ITreasure to not poof on disintegrate.
=> Leng updates - Griff Ledge spawn split due to higher concentration / Kosh body is now present

Source/Kesmai.Server/Game/Items/Equipment/Weapons/Halberds/Polearm.cs
Unit Test below:
private int _weaponPLevel;
[TestCase(1, 2, 8, 1, 0, 1.00),
TestCase(2, 2, 9, 2, 0, 1.00),
TestCase(3, 3, 10, 3, 1, 1.00),
TestCase(4, 3, 11, 4, 1, 1.00),
TestCase(5, 4, 12, 5, 2, 1.00),
TestCase(6, 4, 13, 6, 2, 1.00),
TestCase(7, 5, 14, 7, 3, 1.00)]
public void TestPolearm(int weaponLevel, int minimumDamage, int maximumDamage, int baseAttackBonus, int baseDefenseBonus, double weaponSpeed)
{
_weaponPLevel = weaponLevel;
var weapon = GetPWeaponStats();
Assert.AreEqual(minimumDamage, weapon.MinimumDamage);
Assert.AreEqual(maximumDamage, weapon.MaximumDamage);
Assert.AreEqual(baseAttackBonus, weapon.BaseAttackBonus);
Assert.AreEqual(baseDefenseBonus, weapon.BaseArmorBonus);
Assert.AreEqual(weaponSpeed, weapon.WeaponSpeed);
}
public PoleArmWeapon GetPWeaponStats()
{ …
=> Halberd polearm upgrade path

Source/Kesmai.Server/Game/Items/Equipment/Weapons/Flails/MorningStar.cs
* Unit Test to be attached.
private int _weaponLevel;
[TestCase(1, 2, 8, 1, 0, 1.05),
TestCase(2, 2, 9, 2, 0, 1.1),
TestCase(3, 3, 10, 3, 1, 1.15),
TestCase(4, 3, 11, 4, 1, 1.2),
TestCase(5, 4, 12, 5, 2, 1.25),
TestCase(6, 4, 13, 6, 2, 1.30),
TestCase(7, 5, 14, 6, 2, 1.35)]
public void TestFlail(int weaponLevel, int minimumDamage, int maximumDamage, int baseAttackBonus, int baseDefenseBonus, double weaponSpeed)
{
_weaponLevel = weaponLevel;
var weapon = GetWeaponStats();
Assert.AreEqual(minimumDamage, weapon.MinimumDamage);
Assert.AreEqual(maximumDamage, weapon.MaximumDamage);
Assert.AreEqual(baseAttackBonus, weapon.BaseAttackBonus);
Assert.AreEqual(baseDefenseBonus, weapon.BaseArmorBonus);
Assert.AreEqual(weaponSpeed, weapon.WeaponSpeed);
}
public FlailWeapon GetWeaponStats()
{ …
=> Add Morning Star Upgrade Path

Content/Localization/Enu.xml
Add Dartianian's Robe/Jacket to Dartanian for testing.
=> Dartanian Robe implement

Segments/Axe Glacier.mapproj
My first pull request so let me know if I've messed up.
It appears the Golden Egg was added to the gems folder last year. This change should cause the Goose to drop an egg instead of a nugget.
=> Golden egg

Segments/Axe Glacier.mapproj, Segments/Leng.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Cut all Fire/Ice spells by approx 50%. This PR includes BG + Blackburrow. Moose did Bloodlines on a separate pull.
=> First pass at Tuning Fire/Ice spells for BG + Blackburrow

Content/WorldForge/Components.xml
=> cemetery gates exception fix

Content/Localization/Enu.xml
Initial implementation of the Wizard Boss that will drop the wizard hat. The final boss area is turned off until I finish coding the boss.
=> Initial Implementation of Wizard Lair

Content/Localization/Enu.xml
Fix Labels / Descriptions / Art
=> Fix Labels / Descriptions / Art

Segments/Axe Glacier.mapproj, Segments/Oakvael.mapproj, Segments/Underkingdom.mapproj
Fixes for Bank Ring mis-dumps.
=> AltarCounterFixes

Segments/Annwn.mapproj
Ydmos Blinding from PC
Ydmos Hide is low 
Portal fix
=> Annwn Fixes

Segments/Annwn.mapproj
Annwn - (Compiles)
* Ydmos Hide level reduced to 39
* Ydmos Weapon skill 22 (1 above OL) - Was at 18 (very low)
* BWolf Health Fixed
* Elementals will now use Bonfire in Test Area - Will keep reviewing fight. 
* All bosses have FearBlind status now
Blackburrow (Compiles)
* Weapon to use pathing similar to Wand. (Compiles) 
* Remove PoisonArrow - As it was crashing WF in certain areas. 
Bloodlands (Compiles) 
* Scythe flag updated
=> Various fixes

Segments/Oakvael.mapproj
Konran currently can cause his brother to drop more than one silk finery.
This should dispose of him faster resulting in just one silk finery.
=> Konran Disposed of in milliseconds 

Segments/Oakvael.mapproj
Princess Timer did not work, upping it to a minute.
=> Konran despawns in 10 seconds. (higher than the delay in finery placement)

Content/Data/Body.xml
- Added Body.xml to override current sprites
=> Added body.xml to override current sprites with new 128px versions

Content/Localization/Enu.xml
Added some entries to the localization file so I can shift my weapon messages into CombatMessages to reduce Emote Clutter for bosses.
=> ENU update

Source/Kesmai.Server/Game/Items/Equipment/Rings/BankerRing.cs
Added missing null check to cover edge case.
=> Fix Bankers Ring Client Crash

Source/Kesmai.Server/Game/Items/Equipment/Rings/KnightRing.cs
Added RingID to Knight Ring to allow changes in ItemID.
=> Add RingID to knight ring

Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Phantasm/SummonedDjinn.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Phantasm/SummonedEfreet.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Phantasm/SummonedPhantom.cs
This PR has all pet styles scale relatively evenly so they all remain useful in different situations.
=> Proposed phantasm changes version 2

Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Phantasm/SummonedDjinn.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Phantasm/SummonedEfreet.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Phantasm/SummonedPhantom.cs, Source/Kesmai.Server/Game/Entities/Mobiles/Creatures/Phantasm/SummonedSnake.cs, Source/Kesmai.Server/Game/Items/Equipment/IPetFocus.cs
Add an interface that will be applied to Thaum based items to buff them based on the highest level pet focus item they have equipped.
=> IPetFocus Interface and associated changes

Content/Localization/Enu.xml
* sorrounding != surrounding
* change our stuff to lower case (Kesh / AG)
=> Change spelling in game
